#!/usr/bin/env bash
#
# Run all dotfiles installers and pull all submodules.

git submodule init
git submodule update

set -e

cd "$(dirname $0)"/..

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
